### ISSUE TITLE
其他学校同学可以参与本仓库吗？

### ISSUE THREAD

**Issue by NWdawg** [CDDSCLab/training-plan#23]
## General Question

请问任何同学提交pr都会被review吗？我是其他学校的学生，发现您们的repo很有帮助，想参与学习。

**Comment by ehds** [comment]
> ## General Question
> 
> 请问任何同学提交pr都会被review吗？我是其他学校的学生，发现您们的repo很有帮助，想参与学习。

非常欢迎，我们仓库本来就是开源的，希望大家能够一起交流。

**Comment by NWdawg** [comment]
> > ## General Question
> > 请问任何同学提交pr都会被review吗？我是其他学校的学生，发现您们的repo很有帮助，想参与学习。
> 
> 非常欢迎，我们仓库本来就是开源的，希望大家能够一起交流。

太好了，谢谢！
